### ISSUE TITLE
Pricing Table

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#3] opened 2020-03-13 01:13 UTC
Please add pricing table in a colored box in its own tab 'Pricing'

**Comment by PresidentNick** [comment] 2020-03-16 19:02
I've added the pricing table with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/9b63a5b2fb067763bd6b950aeb291885328fc542) I made the background color the light pastel color the same as the nav. I didn't make any customizations to the pricing table, so it needs the actual pricing and descriptions of the packages, and let me know if you want me to change the colors of the boxes or to add or delete more boxes. This is ready for review on the live site at https://pereiraatxfoto.github.io/pricing/

**Comment by PereiraATXFoto** [comment] 2020-04-27 23:34
We will need more boxes, but leave this pending for now.

**Comment by PresidentNick** [comment] 2020-05-17 22:00
duplicate of #23

**Closed as completed by PresidentNick** 2020-05-17 22:00 UTC
